require 'yaml'


def load_config_yaml
  config = YAML.load_file("config.yaml")
  return config
end

Vagrant.configure("2") do |config|
  config.vagrant.plugins = "vagrant-libvirt"
  config.vm.box = "generic/ubuntu2204"

  yaml_config = load_config_yaml()

  config.vm.define yaml_config["host_name"] do |l2|
    l2.vm.hostname = yaml_config["host_name"]
    l2.vm.provider "libvirt" do |libvirt|
      libvirt.driver = "kvm"
      libvirt.nested = "true"
      libvirt.cpus = yaml_config["cpus"]
      libvirt.memory = yaml_config["memory"]
      # avoid network segment conflict with default network
      libvirt.management_network_name = 'vagrant-net0'
      libvirt.management_network_address = '192.168.124.0/24'
    end
    
    # enable network bridge
    # Ref: https://developer.hashicorp.com/vagrant/docs/networking/public_network
    if yaml_config["network_interface"] != nil then
      network_interface = yaml_config["network_interface"]
      l2.vm.network "public_network", bridge: network_interface, dev: network_interface
    end

    # provisoning
    # Run `vagrant provision` to apply the changes
    if yaml_config["bench_script_path"] != nil
      l2.vm.provision "file", source: yaml_config["bench_script_path"], destination: "/home/vagrant/run-bench.sh"
    end
    if yaml_config["enable_provision_script"] then
        l2.vm.provision "shell", path: "./init.sh"
    end
  end

end
